name: Build

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macOS-13

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
    
    - name: Xcode 15
      run: sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'

    - name: Build
      run: swift build
    
    - name: Test
      run: |
        swift test --enable-code-coverage
        xcrun llvm-cov export -format="lcov" .build/debug/ReactBridgePackageTests.xctest/contents/macos/ReactBridgePackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex='Tests.swift' -ignore-filename-regex='ReactBridgeMacros.swift' > info.lcov
    
    - name: Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
