# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macOS-13

    steps:
    - uses: actions/checkout@v3
    
    - name: XCode 15
      run: sudo xcode-select -s '/Applications/Xcode_15.0.app/Contents/Developer'

    - uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Build
      run: swift build

    - name: Run tests
      run: |
        swift test --enable-code-coverage
        xcrun llvm-cov export -format="lcov" .build/debug/ReactBridgePackageTests.xctest/contents/macos/ReactBridgePackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex='Tests$' -ignore-filename-regex='ReactBridgeMacros.swift' > info.lcov
    
    - name: Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
